### ISSUE TITLE
Entendi porra nenhuma, man

### ISSUE THREAD

**Issue by ClaudioCarvalhoo** [hcaula/hooks-test#1]
Como é essa parada de git hooks? Tu n explica.

**Comment by hcaula** [comment]
Hello, dear @ClaudioCarvalhoo.

This repository is dedicated to test different techniques for hooks, with the hope that I would learn how the hell it works.

But it's really easy and I recommend it.

**Comment by ClaudioCarvalhoo** [comment]
Mas nem tem nada, só fica mexendo no readme esse carai

**Comment by ClaudioCarvalhoo** [comment]
Project owner does not respond to comments with constructive criticism.
3/10, would not recommend.
